### ISSUE TITLE
Update to add User Page? (6.x)

### ISSUE THREAD

**Issue by ghost** [suchmememanyskill/SwitchThemeGuide#1]
Hello,

https://github.com/suchmememanyskill/SwitchThemeGuide/wiki/Installing-your-theme

Doesn't mention MyPage.szs (User_Page) which goes in 0100000000001013.

Also https://github.com/suchmememanyskill/SwitchThemeGuide/wiki/Windows-injector-usage doesn't mention asides from MyPage, Notification. Notification is mentioned on Web injector so on that side it's updated.

**Comment by TehPsychedelic** [comment]
Irrelevant per your comment on this being a guide for the newbie, or something new came out on the homebrew scene.
