### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by acegoal07** [suchmememanyskill/SwitchThemeGuide#2]
i download the theme and activated it rebooted and into the cfw and then hit a black screen i can not get passed.

i used the software and evrything that i was told to use followed the insructionsand it still went wrong.

**Comment by suchmememanyskill** [comment]
What's your cfw/steps you've done/system version/which theme exactly. You're not giving me enough info here to help. (You're probs doing something wrong though, as the guide works)

**Comment by acegoal07** [comment]
i am on version 6.2 i think i cant check at the moment i am using the cfw kosmos

**Comment by suchmememanyskill** [comment]
I'm gonna assume you did something wrong. This is not a place to ask for help anyway. (I've confirmed the guide works).
